# Generated by Django 3.2.16 on 2023-04-24 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='even_location',
            new_name='even_venue',
        ),
        migrations.AddField(
            model_name='event',
            name='even_end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='even_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='even_date',
            field=models.DateField(),
        ),
    ]
