# Generated by Django 3.2.16 on 2023-04-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20230424_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundationcommittee',
            name='designation',
            field=models.CharField(choices=[('CHAIRMAN', 'Chairman'), ('Secretary', 'Secretary'), ('Education and Human Development', 'Education and Human Developmen'), ('Humanitarian', 'Humanitarian Services'), ('Dawa', 'Chairman'), ('Works and Masjid', 'Chairman'), ('Auditor', 'Auditor'), ('Media and Publicity', 'Media and Publicity')], max_length=50),
        ),
    ]
