# Generated by Django 3.2.16 on 2023-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_foundationcommittee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundationcommittee',
            name='display_picture',
            field=models.ImageField(help_text='Width: 800px, Height: 900px', upload_to='pictures/foundation_committee/'),
        ),
    ]
