# Generated by Django 3.2.16 on 2023-04-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_foundationcommittee_qualification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoundationCommittee',
        ),
    ]
